12.0 afc 1103
vertelab/odoo-base pull request #127
Opened 2020-09-30 10:07 UTC by afeli76

Updates res_sni, res_ssyk and partner_daily_notes

2020-10-02 15:56 UTC, FredrikArvas commented on res_ssyk/i18n/sv_SE.po
> +msgstr "Officiel kod, grupp, undergrupp eller detaljerad grupp."
Officiell

2020-10-02 15:57 UTC, FredrikArvas commented on partner_view_360/i18n/sv_SE.po
> +msgstr "E-postadress"
Postadress

2020-10-06 11:39 UTC, MickeHolm requested changes

2020-10-06 11:39 UTC, MickeHolm commented on partner_view_360/i18n/sv_SE.po
> +msgstr "Namn Com Reg Num"
What's this?

2020-10-06 11:39 UTC, MickeHolm commented on partner_view_360/i18n/sv_SE.po
> +msgstr "Personliguppgifter"
Personliga uppgifter

2020-10-12 06:11 UTC, MickeHolm approved these changes

2020-10-12 06:11 UTC, merged