partner_education_views: fixed display name
vertelab/odoo-base pull request #252
Opened 2021-02-22 15:57 UTC by SebastianGieser-Vertel

2021-02-24 12:10 UTC, FredrikArvas commented
Please add change and description in the manifest

2021-02-25 13:16 UTC, nils-vertel approved these changes

2021-02-25 13:16 UTC, nils-vertel commented on partner_education_views/models/education_level.py
> +        for edu_lvl in self:
String concatenation is pretty expensive, its cheaper to build a list and then do "".join(my_list)
In this case it does probably not matter but think of it in the future.

2021-02-25 13:16 UTC, nils-vertel commented on partner_education_views/models/education.py
> +        return data
Missing newline at end of file.

2021-02-25 13:16 UTC, nils-vertel commented on partner_education_views/models/education.py
> +        for education in self:
String concatenation is expensive a better method would be to construct a list and then join it.
Various ways to do this:
 "".join(my_list)
"".join(["string1" or "", string2 or ""])
f'{education.sun_id.name or ""},{education.education_level_id.name or _("None")}'

2021-02-25 15:32 UTC, daerio requested changes
see comments

2021-02-25 15:32 UTC, daerio commented on partner_education/models/education_level.py
> +        res = super(ResPartnerEducationLevel, self).name_get()
We're not using res. Is there a reason to call this super? If not, remove it.

2021-02-25 15:32 UTC, daerio commented on partner_education/models/education.py
> +        res = super(ResPartnerEducation, self).name_get()
We're not using res. Is there a reason to call this super? If not, remove it.

2021-02-25 15:38 UTC, SebastianGieser-Vertel commented
This code will be moved to a different branch.

2021-02-25 15:38 UTC, closed without merging